module.exports = {
  "collect": [
    {
      type: "autogenerated",
      dirName: "collect",
    },
  ],
  css: [
    {
      type: "autogenerated",
      dirName: "css",
    },
  ],
  html: [
    {
      type: "autogenerated",
      dirName: "html",
    },
  ],
  javascript: [
    {
      type: "autogenerated",
      dirName: "javascript",
    },
  ],
}
