module.exports = {
  "collect-intro": [
    {
      type: "autogenerated",
      dirName: "collect",
    },
  ],
  // resources: {
  //   简介: ["resources/resources-intro"],
  //   前端开发: ["resources/ui/css-frameworks/css-frameworks"],
  //   开发工具: ["resources/tools/vs-code-themes/vs-code-themes"],
  // },
};
